version: '2'

services:
    consul:
        build: ./consul
    consului:
        build: ./consului
        ports:
            - 8500:8500
    app:
        build: ./testing/app
        restart: always
        ports:
            - 4000:4000
