consul:
    image: 'flashmedia/consul:dev'
    restart: always
    target_num_containers: 3
    tags:
        - orchestrator-1-do-ny3
consului:
    image: 'flashmedia/consului:dev'
    restart: always
    ports:
        - 8500:8500
    tags:
        - orchestrator-1-do-ny3
app:
    image: 'flashmedia/orchestrator-app:dev'
    restart: always
    ports:
        - 4000:4000
    tags:
        - orchestrator-1-do-ny3
